"""add partial unique index for vendor manager username

Revision ID: 2a8e189ee1f1
Revises: fbf5296ebc8d
Create Date: 2026-07-21 13:06:23.732775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a8e189ee1f1'
down_revision: Union[str, Sequence[str], None] = 'fbf5296ebc8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_employees_vendor_username', 'employees', ['username'], unique=True, postgresql_where=sa.text('company_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_employees_vendor_username', table_name='employees', postgresql_where=sa.text('company_id IS NULL'))
    # ### end Alembic commands ###
