"""add company_id to products

Revision ID: 4f863d87c1d2
Revises: 329770a41489
Create Date: 2026-07-27 13:36:25.060904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f863d87c1d2'
down_revision: Union[str, Sequence[str], None] = '329770a41489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('company_id', sa.BigInteger(), nullable=False))
    op.drop_constraint(op.f('products_sku_key'), 'products', type_='unique')
    op.create_unique_constraint('uq_products_company_sku', 'products', ['company_id', 'sku'])
    op.create_foreign_key(None, 'products', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint('uq_products_company_sku', 'products', type_='unique')
    op.create_unique_constraint(op.f('products_sku_key'), 'products', ['sku'], postgresql_nulls_not_distinct=False)
    op.drop_column('products', 'company_id')
    # ### end Alembic commands ###
