"""add subdomain to companies

Revision ID: 7f1c7c0d6c7c
Revises: 1d40896b7c42
Create Date: 2026-07-27 13:02:54.954861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f1c7c0d6c7c'
down_revision: Union[str, Sequence[str], None] = '1d40896b7c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('subdomain', sa.String(length=63), nullable=False))
    op.create_unique_constraint(None, 'companies', ['subdomain'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'subdomain')
    # ### end Alembic commands ###
